	
------------------- STEP 01 : IMPORT DATASET---------------------------
-- STEP 02 :EXPLORE DATASET	
----------------------------------------------------------------
	
		--EXPLORE ALL  TABLES OBJECT IN PROJECT 
	SELECT * FROM INFORMATION_SCHEMA .TABLES


---------------EXPLORE ALL  CLOUMS OBJECT IN PROJECT------------------------------------
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
			WHERE TABLE_NAME = 'dim_customers'
-----------------------------------------------------------------------------
----------------------------------------------------------------
-- DIMENSON EXPLORATION
-- EXPLORE COUNTRY OUR CUSTOMER COME FROM

	SELECT DISTINCT country FROM dbo.dim_customers
------------------------------------------------------------

------------------------EXPLORE  ALL CATEGRORES MAJOR DIVESON------------------------
	SELECT DISTINCT category,subcategory,product_name FROM dbo.dim_products
	ORDER BY 1,2,3
------------------------------------------------------------------------------------

---------- EXPLORE  ALL DATES(FIIND THE DATE OF FIRST LAST ORDER)-------
	SELECT
		MIN(order_date) as first_orderDate, 
		MAX(order_date) as last_orderDate,
		DATEDIFF(YEAR, MIN(order_date),MAX(order_date)) as order_range_years
	FROM dbo.fact_sales
-------------------------------------------------------------------

	-- FIND THE YOUMGEST AND OLDEST CUSTOMERS
	SELECT
		MIN(birthdate) AS YOUNGEST,
		DATEDIFF(YEAR,MIN(birthdate),GETDATE()) as age_p,
		MAX(birthdate) AS OLDEST,
		DATEDIFF(YEAR,MAX(birthdate),GETDATE()) as age_p
	FROM dbo.dim_customers

-------------------EXPLORE MESURE-------------------------
-- FIND THE TOTAL SALES
	SELECT SUM(sales_amount) as total_sales FROM dbo.fact_sales

-- FIND THE HHOW MANY ITEM SOLD
    SELECT SUM(quantity) as total_quantity FROM dbo.fact_sales

-- FIND AVG PRICE SALES
    SELECT AVG(price) as AVG_PRICE FROM dbo.fact_sales

--- FRIND TOTAL NO OF ORDERES
    SELECT COUNT(order_number) as NO_ORDER FROM dbo.fact_sales

--- FRIND TOTAL NO PF PRODUCT
	SELECT COUNT(product_number) as NO_PRODUCT FROM dbo.dim_products

	-- FIND TOTAL NNO CUSTOMERS
	SELECT  COUNT(customer_number) AS NO_CUSTOMERS FROM dbo.dim_customers

---FIND THE NO OF CUSTOMER THAT PLACED AN ORDER
	SELECT  COUNT(DISTINCT  customer_key) AS NO_CUSTOMERS FROM dbo.fact_sales

-------------------------------------------------------------
-- REPORT THAT SHOW ALL MESURES 
	SELECT  'Total Sales' as measure_name, SUM(sales_amount) as	mesure_value FROM dbo.fact_sales
	UNION ALL
	SELECT  'Total quantety' as measure_name, SUM(quantity) as	mesure_value FROM dbo.fact_sales
	UNION ALL
	SELECT  'Avg price' as measure_name, SUM(price) as	mesure_value FROM dbo.fact_sales
		UNION ALL
	SELECT  'Totalorder' as measure_name, count(order_number) as	mesure_value FROM dbo.fact_sales
	
------------------- MAGINITUDE----------------------------------------------------
-- FIND TOTAL NO CUSTOMER BY COUNTRY
SELECT 
country,
	COUNT(customer_key)  AS TOTAL_CUSTOMER
	FROM dbo.dim_customers
	GROUP BY country
ORDER BY TOTAL_CUSTOMER DESC

-- FIND TOTAL CUSTOMER BY GENDER
SELECT 
gender,
	COUNT(customer_key)  AS TOTAL_CUSTOMER
	FROM dbo.dim_customers
	GROUP BY gender
ORDER BY TOTAL_CUSTOMER DESC

-- FIND TOTAL PRODUCT BY CATEGROY
SELECT 
category,
COUNT(product_key) AS TOTAL_PRDUCT
FROM dbo.dim_products
GROUP BY category
ORDER BY TOTAL_PRDUCT

-- AVG COST INI EACH CATEGORY
SELECT 
category,
AVG(cost) AS AVG_COST
FROM dbo.dim_products
GROUP BY category
ORDER BY AVG_COST DESC

-- WHAT IS THE TOTAL REVANUE GENRETED BY EACH CATEGORY
-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CATEGORY?

SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM dbo.fact_sales AS f
LEFT JOIN dbo.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

---- RANKING ANALYSICS ---------------------
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE?

SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM dbo.fact_sales AS f
LEFT JOIN dbo.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- WHAT ARE THE  5 WORST PERFORMANCE IN TERMS OF SALES
-- WHAT ARE THE 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES?

SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_sales
FROM dbo.fact_sales AS f
LEFT JOIN dbo.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_sales ASC;

-- TOP 10 CUSTOMERS WHO GENERATED THE HIGHEST REVENUE

SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM dbo.fact_sales AS f
LEFT JOIN dbo.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;